; ==========================================================
; ModuleID = 'vit_module'
; Generated by VIT Compiler (Phase 2)
; ==========================================================

source_filename = "vit_module.jslik"
target triple = "x86_64-pc-windows-msvc"

@.fmt_num = private unnamed_addr constant [4 x i8] c"%f\0A\00", align 1
@.fmt_str = private unnamed_addr constant [4 x i8] c"%s\0A\00", align 1
@.fmt_bool_true = private unnamed_addr constant [6 x i8] c"true\0A\00", align 1
@.fmt_bool_false = private unnamed_addr constant [7 x i8] c"false\0A\00", align 1

@.str.0 = private unnamed_addr constant [29 x i8] c"VIT Phase 2 Features Active!\00", align 1
@.str.1 = private unnamed_addr constant [9 x i8] c"isReady:\00", align 1
@.str.2 = private unnamed_addr constant [12 x i8] c"isFinished:\00", align 1
@.str.3 = private unnamed_addr constant [27 x i8] c"Logic AND (true && false):\00", align 1
@.str.4 = private unnamed_addr constant [26 x i8] c"Logic OR (true || false):\00", align 1
@.str.5 = private unnamed_addr constant [54 x i8] c"Function returning inverted bool (checkStatus(true)):\00", align 1

declare i32 @printf(i8*, ...)

define i1 @checkStatus(i1 %flag) {
entry:
  %flag.addr = alloca i1, align 1
  store i1 %flag, i1* %flag.addr, align 1
  %t0 = load i1, i1* %flag.addr, align 1
  %t1 = xor i1 %t0, true
  ret i1 %t1
}

define double @main() {
entry:
  %msg.addr = alloca i8*, align 8
  %t0 = getelementptr inbounds [29 x i8], [29 x i8]* @.str.0, i64 0, i64 0
  store i8* %t0, i8** %msg.addr, align 8
  %t1 = load i8*, i8** %msg.addr, align 8
  %t2 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t3 = call i32 (i8*, ...) @printf(i8* %t2, i8* %t1)
  %isReady.addr = alloca i1, align 1
  store i1 true, i1* %isReady.addr, align 1
  %isFinished.addr = alloca i1, align 1
  store i1 false, i1* %isFinished.addr, align 1
  %t4 = getelementptr inbounds [9 x i8], [9 x i8]* @.str.1, i64 0, i64 0
  %t5 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t6 = call i32 (i8*, ...) @printf(i8* %t5, i8* %t4)
  %t7 = load i1, i1* %isReady.addr, align 1
  br i1 %t7, label %print.true.0, label %print.false.1
print.true.0:
  %t8 = getelementptr inbounds [6 x i8], [6 x i8]* @.fmt_bool_true, i64 0, i64 0
  %t9 = call i32 (i8*, ...) @printf(i8* %t8)
  br label %print.merge.2
print.false.1:
  %t10 = getelementptr inbounds [7 x i8], [7 x i8]* @.fmt_bool_false, i64 0, i64 0
  %t11 = call i32 (i8*, ...) @printf(i8* %t10)
  br label %print.merge.2
print.merge.2:
  %t12 = getelementptr inbounds [12 x i8], [12 x i8]* @.str.2, i64 0, i64 0
  %t13 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t14 = call i32 (i8*, ...) @printf(i8* %t13, i8* %t12)
  %t15 = load i1, i1* %isFinished.addr, align 1
  br i1 %t15, label %print.true.3, label %print.false.4
print.true.3:
  %t16 = getelementptr inbounds [6 x i8], [6 x i8]* @.fmt_bool_true, i64 0, i64 0
  %t17 = call i32 (i8*, ...) @printf(i8* %t16)
  br label %print.merge.5
print.false.4:
  %t18 = getelementptr inbounds [7 x i8], [7 x i8]* @.fmt_bool_false, i64 0, i64 0
  %t19 = call i32 (i8*, ...) @printf(i8* %t18)
  br label %print.merge.5
print.merge.5:
  %t20 = getelementptr inbounds [27 x i8], [27 x i8]* @.str.3, i64 0, i64 0
  %t21 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t22 = call i32 (i8*, ...) @printf(i8* %t21, i8* %t20)
  %t23 = load i1, i1* %isReady.addr, align 1
  br i1 %t23, label %log.rhs.6, label %log.merge.7
log.rhs.6:
  %t25 = load i1, i1* %isFinished.addr, align 1
  br label %log.merge.7
log.merge.7:
  %t24 = phi i1 [ false, %print.merge.5 ], [ %t25, %log.rhs.6 ]
  br i1 %t24, label %print.true.8, label %print.false.9
print.true.8:
  %t26 = getelementptr inbounds [6 x i8], [6 x i8]* @.fmt_bool_true, i64 0, i64 0
  %t27 = call i32 (i8*, ...) @printf(i8* %t26)
  br label %print.merge.10
print.false.9:
  %t28 = getelementptr inbounds [7 x i8], [7 x i8]* @.fmt_bool_false, i64 0, i64 0
  %t29 = call i32 (i8*, ...) @printf(i8* %t28)
  br label %print.merge.10
print.merge.10:
  %t30 = getelementptr inbounds [26 x i8], [26 x i8]* @.str.4, i64 0, i64 0
  %t31 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t32 = call i32 (i8*, ...) @printf(i8* %t31, i8* %t30)
  %t33 = load i1, i1* %isReady.addr, align 1
  br i1 %t33, label %log.merge.12, label %log.rhs.11
log.rhs.11:
  %t35 = load i1, i1* %isFinished.addr, align 1
  br label %log.merge.12
log.merge.12:
  %t34 = phi i1 [ true, %print.merge.10 ], [ %t35, %log.rhs.11 ]
  br i1 %t34, label %print.true.13, label %print.false.14
print.true.13:
  %t36 = getelementptr inbounds [6 x i8], [6 x i8]* @.fmt_bool_true, i64 0, i64 0
  %t37 = call i32 (i8*, ...) @printf(i8* %t36)
  br label %print.merge.15
print.false.14:
  %t38 = getelementptr inbounds [7 x i8], [7 x i8]* @.fmt_bool_false, i64 0, i64 0
  %t39 = call i32 (i8*, ...) @printf(i8* %t38)
  br label %print.merge.15
print.merge.15:
  %t40 = getelementptr inbounds [54 x i8], [54 x i8]* @.str.5, i64 0, i64 0
  %t41 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t42 = call i32 (i8*, ...) @printf(i8* %t41, i8* %t40)
  %inv.addr = alloca i1, align 1
  %t43 = call i1 @checkStatus(i1 true)
  store i1 %t43, i1* %inv.addr, align 1
  %t44 = load i1, i1* %inv.addr, align 1
  br i1 %t44, label %print.true.16, label %print.false.17
print.true.16:
  %t45 = getelementptr inbounds [6 x i8], [6 x i8]* @.fmt_bool_true, i64 0, i64 0
  %t46 = call i32 (i8*, ...) @printf(i8* %t45)
  br label %print.merge.18
print.false.17:
  %t47 = getelementptr inbounds [7 x i8], [7 x i8]* @.fmt_bool_false, i64 0, i64 0
  %t48 = call i32 (i8*, ...) @printf(i8* %t47)
  br label %print.merge.18
print.merge.18:
  ret double 0.0
}

