#include "codegen/LLVMCodeGen.h"
#include <iomanip>

namespace vit {

std::string LLVMCodeGen::newReg() {
    return "%t" + std::to_string(regCounter++);
}

std::string LLVMCodeGen::newLabel(const std::string& prefix) {
    return prefix + "." + std::to_string(labelCounter++);
}

void LLVMCodeGen::emitIndent() {
    irStream << "  ";
}

std::string LLVMCodeGen::generateIR(ProgramASTNode* program) {
    irStream.str("");
    irStream.clear();
    regCounter = 0;
    labelCounter = 0;
    symbolTable.clear();

    visit(program);
    return irStream.str();
}

void LLVMCodeGen::visit(ProgramASTNode* node) {
    irStream << "; ==========================================================\n";
    irStream << "; ModuleID = 'vit_module'\n";
    irStream << "; Generated by VIT Compiler (Phase 1 MVP)\n";
    irStream << "; ==========================================================\n\n";
    irStream << "source_filename = \"vit_module.jslik\"\n";
    irStream << "target triple = \"x86_64-pc-windows-msvc\"\n\n";

    irStream << "@.fmt_print = private unnamed_addr constant [4 x i8] c\"%f\\0A\\00\", align 1\n\n";

    irStream << "declare i32 @printf(i8*, ...)\n\n";

    for (const auto& func : node->getFunctions()) {
        func->accept(this);
    }
}

void LLVMCodeGen::visit(FunctionDeclASTNode* node) {
    symbolTable.clear();
    regCounter = 0;
    blockHasTerminator = false;

    irStream << "define double @" << node->getName() << "(";
    const auto& params = node->getParams();
    for (size_t i = 0; i < params.size(); ++i) {
        irStream << "double %" << params[i].name;
        if (i + 1 < params.size()) irStream << ", ";
    }
    irStream << ") {\n";
    irStream << "entry:\n";

    // Allocate stack slots for parameters
    for (const auto& param : params) {
        std::string addrReg = "%" + param.name + ".addr";
        emitIndent();
        irStream << addrReg << " = alloca double, align 8\n";
        emitIndent();
        irStream << "store double %" << param.name << ", double* " << addrReg << ", align 8\n";
        symbolTable[param.name] = addrReg;
    }

    if (node->getBody()) {
        node->getBody()->accept(this);
    }

    // Default fallback return 0.0 if not explicitly returned
    if (!blockHasTerminator) {
        emitIndent();
        irStream << "ret double 0.000000e+00\n";
    }
    irStream << "}\n\n";
}

void LLVMCodeGen::visit(BlockASTNode* node) {
    for (const auto& stmt : node->getStatements()) {
        stmt->accept(this);
    }
}

void LLVMCodeGen::visit(VarDeclASTNode* node) {
    std::string addrReg = "%" + node->getName() + ".addr";
    symbolTable[node->getName()] = addrReg;

    emitIndent();
    irStream << addrReg << " = alloca double, align 8\n";

    if (node->getInitializer()) {
        node->getInitializer()->accept(this);
        std::string valReg = lastResultReg;

        emitIndent();
        irStream << "store double " << valReg << ", double* " << addrReg << ", align 8\n";
    }
}

void LLVMCodeGen::visit(AssignmentASTNode* node) {
    auto it = symbolTable.find(node->getName());
    std::string addrReg = (it != symbolTable.end()) ? it->second : ("%" + node->getName() + ".addr");

    if (node->getValue()) {
        node->getValue()->accept(this);
        std::string valReg = lastResultReg;

        emitIndent();
        irStream << "store double " << valReg << ", double* " << addrReg << ", align 8\n";
    }
}

void LLVMCodeGen::visit(NumberLiteralASTNode* node) {
    // LLVM IR floating point format
    std::ostringstream ss;
    ss << std::scientific << std::setprecision(6) << node->getValue();
    // Convert to simple decimal double format e.g. 10.000000 or 1.000000e+01
    std::ostringstream simpleSS;
    simpleSS << node->getValue();
    std::string str = simpleSS.str();
    if (str.find('.') == std::string::npos && str.find('e') == std::string::npos) {
        str += ".0";
    }
    lastResultReg = str;
}

void LLVMCodeGen::visit(VariableExprASTNode* node) {
    auto it = symbolTable.find(node->getName());
    std::string addrReg = (it != symbolTable.end()) ? it->second : ("%" + node->getName() + ".addr");

    std::string loadReg = newReg();
    emitIndent();
    irStream << loadReg << " = load double, double* " << addrReg << ", align 8\n";
    lastResultReg = loadReg;
}

void LLVMCodeGen::visit(BinaryOpASTNode* node) {
    node->getLeft()->accept(this);
    std::string lhs = lastResultReg;

    node->getRight()->accept(this);
    std::string rhs = lastResultReg;

    std::string resultReg = newReg();
    const std::string& op = node->getOp();

    if (op == "+") {
        emitIndent();
        irStream << resultReg << " = fadd double " << lhs << ", " << rhs << "\n";
    } else if (op == "-") {
        emitIndent();
        irStream << resultReg << " = fsub double " << lhs << ", " << rhs << "\n";
    } else if (op == "*") {
        emitIndent();
        irStream << resultReg << " = fmul double " << lhs << ", " << rhs << "\n";
    } else if (op == "/") {
        emitIndent();
        irStream << resultReg << " = fdiv double " << lhs << ", " << rhs << "\n";
    } else if (op == ">" || op == "<" || op == "==" || op == "!=" || op == ">=" || op == "<=") {
        std::string condCode = "oeq";
        if (op == ">") condCode = "ogt";
        else if (op == "<") condCode = "olt";
        else if (op == "==") condCode = "oeq";
        else if (op == "!=") condCode = "one";
        else if (op == ">=") condCode = "oge";
        else if (op == "<=") condCode = "ole";

        std::string cmpReg = newReg();
        emitIndent();
        irStream << cmpReg << " = fcmp " << condCode << " double " << lhs << ", " << rhs << "\n";

        // Convert i1 boolean to double (1.0 or 0.0)
        emitIndent();
        irStream << resultReg << " = uitofp i1 " << cmpReg << " to double\n";
    }

    lastResultReg = resultReg;
}

void LLVMCodeGen::visit(IfASTNode* node) {
    node->getCondition()->accept(this);
    std::string condVal = lastResultReg;

    // Convert condition (double) to i1 boolean for branching
    std::string condI1 = newReg();
    emitIndent();
    irStream << condI1 << " = fcmp one double " << condVal << ", 0.000000e+00\n";

    std::string thenLabel = newLabel("then");
    std::string elseLabel = newLabel("else");
    std::string mergeLabel = newLabel("merge");

    if (node->getElseBlock()) {
        emitIndent();
        irStream << "br i1 " << condI1 << ", label %" << thenLabel << ", label %" << elseLabel << "\n";

        irStream << thenLabel << ":\n";
        node->getThenBlock()->accept(this);
        emitIndent();
        irStream << "br label %" << mergeLabel << "\n";

        irStream << elseLabel << ":\n";
        node->getElseBlock()->accept(this);
        emitIndent();
        irStream << "br label %" << mergeLabel << "\n";
    } else {
        emitIndent();
        irStream << "br i1 " << condI1 << ", label %" << thenLabel << ", label %" << mergeLabel << "\n";

        irStream << thenLabel << ":\n";
        node->getThenBlock()->accept(this);
        emitIndent();
        irStream << "br label %" << mergeLabel << "\n";
    }

    irStream << mergeLabel << ":\n";
}

void LLVMCodeGen::visit(CallExprASTNode* node) {
    std::vector<std::string> argRegs;
    for (const auto& arg : node->getArgs()) {
        arg->accept(this);
        argRegs.push_back(lastResultReg);
    }

    std::string callReg = newReg();
    emitIndent();
    irStream << callReg << " = call double @" << node->getCallee() << "(";
    for (size_t i = 0; i < argRegs.size(); ++i) {
        irStream << "double " << argRegs[i];
        if (i + 1 < argRegs.size()) irStream << ", ";
    }
    irStream << ")\n";

    lastResultReg = callReg;
}

void LLVMCodeGen::visit(PrintASTNode* node) {
    if (node->getExpression()) {
        node->getExpression()->accept(this);
        std::string valReg = lastResultReg;

        std::string strPtr = newReg();
        emitIndent();
        irStream << strPtr << " = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_print, i64 0, i64 0\n";

        std::string printCall = newReg();
        emitIndent();
        irStream << printCall << " = call i32 (i8*, ...) @printf(i8* " << strPtr << ", double " << valReg << ")\n";
    }
}

void LLVMCodeGen::visit(ReturnASTNode* node) {
    blockHasTerminator = true;
    if (node->getValue()) {
        node->getValue()->accept(this);
        std::string retVal = lastResultReg;
        emitIndent();
        irStream << "ret double " << retVal << "\n";
    } else {
        emitIndent();
        irStream << "ret double 0.000000e+00\n";
    }
}

} // namespace vit
