#include "codegen/LLVMCodeGen.h"
#include "lexer/Lexer.h"
#include "parser/Parser.h"
#include <iomanip>

namespace vit {

std::string LLVMCodeGen::newReg() {
    return "%t" + std::to_string(regCounter++);
}

const VarSymbol* LLVMCodeGen::findSymbol(const std::string& name) const {
    auto it = symbolTable.find(name);
    if (it != symbolTable.end()) return &it->second;
    auto git = globalSymbolTable.find(name);
    if (git != globalSymbolTable.end()) return &git->second;
    return nullptr;
}

std::string LLVMCodeGen::newLabel(const std::string& prefix) {
    return prefix + "." + std::to_string(labelCounter++);
}

void LLVMCodeGen::emitIndent() {
    irStream << "  ";
}

std::string LLVMCodeGen::resolveType(const std::string& typeName) const {
    auto it = typeAliases.find(typeName);
    if (it != typeAliases.end()) {
        return resolveType(it->second);
    }
    return typeName;
}

std::string LLVMCodeGen::getLLVMType(const std::string& vitTypeRaw) {
    std::string vitType = resolveType(vitTypeRaw);
    if (!vitType.empty() && vitType.back() == '?') {
        vitType.pop_back();
    }
    size_t anglePos = vitType.find('<');
    if (anglePos != std::string::npos) {
        vitType = vitType.substr(0, anglePos);
    }
    if (vitType == "boolean") return "i1";
    if (vitType == "int" || vitType == "i64" || vitType == "integer" || vitType == "i32") return "i64";
    if (vitType == "float" || vitType == "f64" || vitType == "number") return "double";
    if (vitType == "string") return "i8*";
    if (vitType == "null") return "i8*";
    if (vitType == "void") return "void";
    if (vitType == "Promise" || vitType == "Channel" || vitType == "Thread") return "i8*";
    if (vitType.size() > 2 && vitType.substr(vitType.size() - 2) == "[]") {
        return "double*"; // Pointer to heap array
    }
    if (vitType.find("=>") != std::string::npos || (!vitType.empty() && vitType[0] == '(') || vitType == "function") {
        return "i8*";
    }
    auto it = structs.find(vitType);
    if (it != structs.end()) {
        return "%struct." + vitType + "*";
    }
    if (enums.count(vitType)) {
        return "%struct." + vitType + "*";
    }
    return "double";
}

std::string LLVMCodeGen::generateIR(ProgramASTNode* program, const std::string& targetTriple) {
    irStream.str("");
    irStream.clear();
    globalDefsStream.str("");
    globalDefsStream.clear();

    regCounter = 0;
    labelCounter = 0;
    stringCounter = 0;
    lambdaCounter = 0;
    symbolTable.clear();
    globalSymbolTable.clear();
    functionReturnTypes.clear();
    functionReturnTypes["fflush"] = "i32";
    functionReturnTypes["puts"] = "i32";
    functionReturnTypes["printf"] = "i32";
    functionReturnTypes["sprintf"] = "i32";
    functionReturnTypes["malloc"] = "string";
    functionReturnTypes["free"] = "void";
    functionReturnTypes["strlen"] = "int";
    functionReturnTypes["strcmp"] = "i32";
    functionReturnTypes["strcpy"] = "string";
    functionReturnTypes["strcat"] = "string";
    functionReturnTypes["exit"] = "void";
    structs.clear();
    enums.clear();
    declaredFunctions.clear();
    declaredFunctions.insert("printf");
    declaredFunctions.insert("sprintf");
    declaredFunctions.insert("malloc");
    declaredFunctions.insert("free");
    declaredFunctions.insert("strlen");
    declaredFunctions.insert("strcmp");
    declaredFunctions.insert("strcpy");
    declaredFunctions.insert("strcat");
    declaredFunctions.insert("exit");
    declaredFunctions.insert("__vit_init_args");
    declaredFunctions.insert("vit_thread_spawn");
    declaredFunctions.insert("vit_thread_join");
    declaredFunctions.insert("vit_thread_detach");
    declaredFunctions.insert("vit_channel_create");
    declaredFunctions.insert("vit_channel_send");
    declaredFunctions.insert("vit_channel_receive");
    declaredFunctions.insert("vit_channel_free");
    declaredFunctions.insert("vit_promise_create");
    declaredFunctions.insert("vit_promise_resolve");
    declaredFunctions.insert("vit_promise_await");
    declaredFunctions.insert("vit_promise_free");
    declaredFunctions.insert("vit_task_spawn");
    typeAliases.clear();
    loopStack.clear();

    visit(program);

#ifdef _WIN32
    std::string effectiveTriple = targetTriple.empty() ? "x86_64-w64-mingw32" : targetTriple;
#else
    std::string effectiveTriple = targetTriple.empty() ? "x86_64-unknown-linux-gnu" : targetTriple;
#endif

    std::stringstream fullModule;
    fullModule << "; ==========================================================\n";
    fullModule << "; ModuleID = 'vit_module'\n";
    fullModule << "; Generated by VIT Compiler (Phase 14)\n";
    fullModule << "; ==========================================================\n\n";
    fullModule << "source_filename = \"vit_module.vit\"\n";
    fullModule << "target triple = \"" << effectiveTriple << "\"\n\n";

    fullModule << "@.fmt_num = private unnamed_addr constant [4 x i8] c\"%f\\0A\\00\", align 1\n";
    fullModule << "@.fmt_int = private unnamed_addr constant [6 x i8] c\"%lld\\0A\\00\", align 1\n";
    fullModule << "@.fmt_str = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\", align 1\n";
    fullModule << "@.fmt_bool_true = private unnamed_addr constant [6 x i8] c\"true\\0A\\00\", align 1\n";
    fullModule << "@.fmt_bool_false = private unnamed_addr constant [7 x i8] c\"false\\0A\\00\", align 1\n";
    fullModule << "@.str.bounds_panic = private unnamed_addr constant [21 x i8] c\"Index out of bounds\\0A\\00\", align 1\n\n";

    fullModule << globalDefsStream.str();
    if (!globalDefsStream.str().empty()) fullModule << "\n";

    fullModule << "declare i32 @printf(i8*, ...)\n";
    fullModule << "declare i32 @sprintf(i8*, i8*, ...)\n";
    fullModule << "declare i32 @fflush(i8*)\n";
    fullModule << "declare i8* @malloc(i64)\n";
    fullModule << "declare void @free(i8*)\n";
    fullModule << "declare i64 @strlen(i8*)\n";
    fullModule << "declare i32 @strcmp(i8*, i8*)\n";
    fullModule << "declare i8* @strcpy(i8*, i8*)\n";
    fullModule << "declare i8* @strcat(i8*, i8*)\n";
    fullModule << "declare void @exit(i32)\n";
    fullModule << "declare void @__vit_init_args(i32, i8**)\n\n";
    fullModule << "declare i8* @vit_thread_spawn(i8*, i8*)\n";
    fullModule << "declare void @vit_thread_join(i8*)\n";
    fullModule << "declare void @vit_thread_detach(i8*)\n";
    fullModule << "declare i8* @vit_channel_create()\n";
    fullModule << "declare void @vit_channel_send(i8*, double)\n";
    fullModule << "declare double @vit_channel_receive(i8*)\n";
    fullModule << "declare void @vit_channel_free(i8*)\n";
    fullModule << "declare i8* @vit_promise_create()\n";
    fullModule << "declare void @vit_promise_resolve(i8*, double)\n";
    fullModule << "declare double @vit_promise_await(i8*)\n";
    fullModule << "declare void @vit_promise_free(i8*)\n";
    fullModule << "declare void @vit_task_spawn(i8*, i8*)\n\n";

    fullModule << "define void @__vit_panic(i8* %msg) {\n";
    fullModule << "  %fmt = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0\n";
    fullModule << "  %call = call i32 (i8*, ...) @printf(i8* %fmt, i8* %msg)\n";
    fullModule << "  call void @exit(i32 1)\n";
    fullModule << "  unreachable\n";
    fullModule << "}\n\n";

    fullModule << irStream.str();

    return fullModule.str();
}

} // namespace vit
