#include "codegen/LLVMCodeGen.h"
#include <iomanip>

namespace vit {

std::string LLVMCodeGen::newReg() {
    return "%t" + std::to_string(regCounter++);
}

std::string LLVMCodeGen::newLabel(const std::string& prefix) {
    return prefix + "." + std::to_string(labelCounter++);
}

void LLVMCodeGen::emitIndent() {
    irStream << "  ";
}

std::string LLVMCodeGen::getLLVMType(const std::string& vitType) {
    if (vitType == "boolean") return "i1";
    if (vitType == "string") return "i8*";
    if (vitType == "void") return "void";
    if (vitType.size() > 2 && vitType.substr(vitType.size() - 2) == "[]") {
        return "double*"; // Pointer to heap array
    }
    auto it = structs.find(vitType);
    if (it != structs.end()) {
        return "%struct." + vitType + "*";
    }
    return "double";
}

std::string LLVMCodeGen::generateIR(ProgramASTNode* program) {
    irStream.str("");
    irStream.clear();
    globalDefsStream.str("");
    globalDefsStream.clear();

    regCounter = 0;
    labelCounter = 0;
    stringCounter = 0;
    symbolTable.clear();
    functionReturnTypes.clear();
    structs.clear();
    loopStack.clear();

    visit(program);

    std::stringstream fullModule;
    fullModule << "; ==========================================================\n";
    fullModule << "; ModuleID = 'vit_module'\n";
    fullModule << "; Generated by VIT Compiler (Phase 3)\n";
    fullModule << "; ==========================================================\n\n";
    fullModule << "source_filename = \"vit_module.jslik\"\n";
    fullModule << "target triple = \"x86_64-pc-windows-msvc\"\n\n";

    fullModule << "@.fmt_num = private unnamed_addr constant [4 x i8] c\"%f\\0A\\00\", align 1\n";
    fullModule << "@.fmt_str = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\", align 1\n";
    fullModule << "@.fmt_bool_true = private unnamed_addr constant [6 x i8] c\"true\\0A\\00\", align 1\n";
    fullModule << "@.fmt_bool_false = private unnamed_addr constant [7 x i8] c\"false\\0A\\00\", align 1\n\n";

    fullModule << globalDefsStream.str();
    if (!globalDefsStream.str().empty()) fullModule << "\n";

    fullModule << "declare i32 @printf(i8*, ...)\n";
    fullModule << "declare i8* @malloc(i64)\n";
    fullModule << "declare void @free(i8*)\n\n";
    fullModule << irStream.str();

    return fullModule.str();
}

void LLVMCodeGen::visit(ProgramASTNode* node) {
    for (const auto& func : node->getFunctions()) {
        functionReturnTypes[func->getName()] = func->getReturnType();
    }

    for (const auto& stmt : node->getTopLevelStatements()) {
        if (stmt->getType() == NodeType::StructDecl) {
            stmt->accept(this);
        }
    }

    for (const auto& func : node->getFunctions()) {
        func->accept(this);
    }
}

void LLVMCodeGen::visit(StructDeclASTNode* node) {
    StructInfo info;
    info.name = node->getName();
    info.fields = node->getFields();
    for (int i = 0; i < (int)node->getFields().size(); ++i) {
        info.fieldIndices[node->getFields()[i].first] = i;
    }
    structs[node->getName()] = info;

    globalDefsStream << "%struct." << node->getName() << " = type { ";
    for (size_t i = 0; i < node->getFields().size(); ++i) {
        globalDefsStream << getLLVMType(node->getFields()[i].second);
        if (i + 1 < node->getFields().size()) globalDefsStream << ", ";
    }
    globalDefsStream << " }\n";
}

void LLVMCodeGen::visit(FunctionDeclASTNode* node) {
    symbolTable.clear();
    regCounter = 0;
    blockHasTerminator = false;

    currentFunctionReturnType = node->getReturnType();
    std::string llvmRetType = getLLVMType(currentFunctionReturnType);

    if (node->getIsExtern()) {
        irStream << "declare " << llvmRetType << " @" << node->getName() << "(";
        const auto& params = node->getParams();
        for (size_t i = 0; i < params.size(); ++i) {
            irStream << getLLVMType(params[i].typeName);
            if (i + 1 < params.size()) irStream << ", ";
        }
        irStream << ")\n\n";
        return;
    }

    irStream << "define " << llvmRetType << " @" << node->getName() << "(";
    const auto& params = node->getParams();
    for (size_t i = 0; i < params.size(); ++i) {
        std::string pType = getLLVMType(params[i].typeName);
        irStream << pType << " %" << params[i].name;
        if (i + 1 < params.size()) irStream << ", ";
    }
    irStream << ") {\n";
    irStream << "entry:\n";
    currentBlockLabel = "entry";

    for (const auto& param : params) {
        std::string addrReg = "%" + param.name + ".addr";
        std::string pType = getLLVMType(param.typeName);

        emitIndent();
        irStream << addrReg << " = alloca " << pType << ", align 8\n";
        emitIndent();
        irStream << "store " << pType << " %" << param.name << ", " << pType << "* " << addrReg << ", align 8\n";

        symbolTable[param.name] = {addrReg, param.typeName};
    }

    if (node->getBody()) {
        node->getBody()->accept(this);
    }

    if (!blockHasTerminator) {
        emitIndent();
        if (llvmRetType == "void") {
            irStream << "ret void\n";
        } else if (llvmRetType == "i1") {
            irStream << "ret i1 false\n";
        } else if (llvmRetType == "i8*" || llvmRetType.back() == '*') {
            irStream << "ret " << llvmRetType << " null\n";
        } else {
            irStream << "ret double 0.000000e+00\n";
        }
    }
    irStream << "}\n\n";
}

void LLVMCodeGen::visit(BlockASTNode* node) {
    for (const auto& stmt : node->getStatements()) {
        stmt->accept(this);
    }
}

void LLVMCodeGen::visit(VarDeclASTNode* node) {
    std::string addrReg = "%" + node->getName() + ".addr";
    std::string typeName = node->getTypeName();

    std::string valReg = "";
    if (node->getInitializer()) {
        node->getInitializer()->accept(this);
        valReg = lastResultReg;
        if (typeName.empty()) {
            typeName = lastResultType;
        }
    }

    if (typeName.empty()) typeName = "number";
    std::string llvmType = getLLVMType(typeName);

    emitIndent();
    irStream << addrReg << " = alloca " << llvmType << ", align 8\n";
    symbolTable[node->getName()] = {addrReg, typeName};

    if (auto it = structs.find(typeName); it != structs.end()) {
        // Allocate struct memory on stack
        std::string allocReg = newReg();
        emitIndent();
        irStream << allocReg << " = alloca %struct." << typeName << ", align 8\n";
        emitIndent();
        irStream << "store %struct." << typeName << "* " << allocReg << ", %struct." << typeName << "** " << addrReg << ", align 8\n";
    }

    if (!valReg.empty()) {
        emitIndent();
        irStream << "store " << llvmType << " " << valReg << ", " << llvmType << "* " << addrReg << ", align 8\n";
    }
}

void LLVMCodeGen::visit(AssignmentASTNode* node) {
    auto it = symbolTable.find(node->getName());
    std::string addrReg = (it != symbolTable.end()) ? it->second.addrReg : ("%" + node->getName() + ".addr");
    std::string typeName = (it != symbolTable.end()) ? it->second.typeName : "number";

    std::string llvmType = getLLVMType(typeName);

    if (node->getValue()) {
        node->getValue()->accept(this);
        std::string valReg = lastResultReg;

        emitIndent();
        irStream << "store " << llvmType << " " << valReg << ", " << llvmType << "* " << addrReg << ", align 8\n";
    }
}

void LLVMCodeGen::visit(MemberAssignmentASTNode* node) {
    node->getTarget()->accept(this);
    std::string structPtrReg = lastResultReg;
    std::string structType = lastResultType;

    auto it = structs.find(structType);
    if (it != structs.end()) {
        int idx = it->second.fieldIndices[node->getMember()];
        std::string fieldType = it->second.fields[idx].second;
        std::string llvmFieldType = getLLVMType(fieldType);

        std::string gepReg = newReg();
        emitIndent();
        irStream << gepReg << " = getelementptr inbounds %struct." << structType << ", %struct." << structType << "* " << structPtrReg << ", i32 0, i32 " << idx << "\n";

        node->getValue()->accept(this);
        std::string valReg = lastResultReg;

        emitIndent();
        irStream << "store " << llvmFieldType << " " << valReg << ", " << llvmFieldType << "* " << gepReg << ", align 8\n";
    }
}

void LLVMCodeGen::visit(ArrayAssignmentASTNode* node) {
    node->getArray()->accept(this);
    std::string arrPtrReg = lastResultReg;

    node->getIndex()->accept(this);
    std::string idxReg = lastResultReg;
    std::string idxI64 = idxReg;
    if (lastResultType == "number") {
        idxI64 = newReg();
        emitIndent();
        irStream << idxI64 << " = fptosi double " << idxReg << " to i64\n";
    }

    std::string gepReg = newReg();
    emitIndent();
    irStream << gepReg << " = getelementptr inbounds double, double* " << arrPtrReg << ", i64 " << idxI64 << "\n";

    node->getValue()->accept(this);
    std::string valReg = lastResultReg;

    emitIndent();
    irStream << "store double " << valReg << ", double* " << gepReg << ", align 8\n";
}

void LLVMCodeGen::visit(NumberLiteralASTNode* node) {
    std::ostringstream simpleSS;
    simpleSS << node->getValue();
    std::string str = simpleSS.str();
    if (str.find('.') == std::string::npos && str.find('e') == std::string::npos) {
        str += ".0";
    }
    lastResultReg = str;
    lastResultType = "number";
}

void LLVMCodeGen::visit(BooleanLiteralASTNode* node) {
    lastResultReg = node->getValue() ? "true" : "false";
    lastResultType = "boolean";
}

void LLVMCodeGen::visit(StringLiteralASTNode* node) {
    std::string strVal = node->getValue();
    std::string globalName = "@.str." + std::to_string(stringCounter++);

    std::string irStr;
    size_t byteCount = 0;
    for (char c : strVal) {
        if (c == '\n') { irStr += "\\0A"; byteCount++; }
        else if (c == '\t') { irStr += "\\09"; byteCount++; }
        else if (c == '\r') { irStr += "\\0D"; byteCount++; }
        else if (c == '"') { irStr += "\\22"; byteCount++; }
        else if (c == '\\') { irStr += "\\5C"; byteCount++; }
        else { irStr += c; byteCount++; }
    }
    irStr += "\\00";
    byteCount += 1; // null terminator

    globalDefsStream << globalName << " = private unnamed_addr constant [" << byteCount << " x i8] c\"" << irStr << "\", align 1\n";

    std::string ptrReg = newReg();
    emitIndent();
    irStream << ptrReg << " = getelementptr inbounds [" << byteCount << " x i8], [" << byteCount << " x i8]* " << globalName << ", i64 0, i64 0\n";

    lastResultReg = ptrReg;
    lastResultType = "string";
}

void LLVMCodeGen::visit(ArrayLiteralASTNode* node) {
    size_t count = node->getElements().size();

    std::string mallocCall = newReg();
    emitIndent();
    irStream << mallocCall << " = call i8* @malloc(i64 " << (count * 8) << ")\n";

    std::string ptrReg = newReg();
    emitIndent();
    irStream << ptrReg << " = bitcast i8* " << mallocCall << " to double*\n";

    for (size_t i = 0; i < count; ++i) {
        node->getElements()[i]->accept(this);
        std::string elemVal = lastResultReg;

        std::string gepReg = newReg();
        emitIndent();
        irStream << gepReg << " = getelementptr inbounds double, double* " << ptrReg << ", i64 " << i << "\n";
        emitIndent();
        irStream << "store double " << elemVal << ", double* " << gepReg << ", align 8\n";
    }

    lastResultReg = ptrReg;
    lastResultType = "number[]";
}

void LLVMCodeGen::visit(VariableExprASTNode* node) {
    auto it = symbolTable.find(node->getName());
    std::string addrReg = (it != symbolTable.end()) ? it->second.addrReg : ("%" + node->getName() + ".addr");
    std::string typeName = (it != symbolTable.end()) ? it->second.typeName : "number";

    std::string llvmType = getLLVMType(typeName);

    std::string loadReg = newReg();
    emitIndent();
    irStream << loadReg << " = load " << llvmType << ", " << llvmType << "* " << addrReg << ", align 8\n";
    lastResultReg = loadReg;
    lastResultType = typeName;
}

void LLVMCodeGen::visit(MemberAccessASTNode* node) {
    node->getTarget()->accept(this);
    std::string structPtrReg = lastResultReg;
    std::string structType = lastResultType;

    auto it = structs.find(structType);
    if (it != structs.end()) {
        int idx = it->second.fieldIndices[node->getMember()];
        std::string fieldType = it->second.fields[idx].second;
        std::string llvmFieldType = getLLVMType(fieldType);

        std::string gepReg = newReg();
        emitIndent();
        irStream << gepReg << " = getelementptr inbounds %struct." << structType << ", %struct." << structType << "* " << structPtrReg << ", i32 0, i32 " << idx << "\n";

        std::string valReg = newReg();
        emitIndent();
        irStream << valReg << " = load " << llvmFieldType << ", " << llvmFieldType << "* " << gepReg << ", align 8\n";

        lastResultReg = valReg;
        lastResultType = fieldType;
    }
}

void LLVMCodeGen::visit(ArrayAccessASTNode* node) {
    node->getArray()->accept(this);
    std::string arrPtrReg = lastResultReg;

    node->getIndex()->accept(this);
    std::string idxReg = lastResultReg;
    std::string idxI64 = idxReg;
    if (lastResultType == "number") {
        idxI64 = newReg();
        emitIndent();
        irStream << idxI64 << " = fptosi double " << idxReg << " to i64\n";
    }

    std::string gepReg = newReg();
    emitIndent();
    irStream << gepReg << " = getelementptr inbounds double, double* " << arrPtrReg << ", i64 " << idxI64 << "\n";

    std::string valReg = newReg();
    emitIndent();
    irStream << valReg << " = load double, double* " << gepReg << ", align 8\n";

    lastResultReg = valReg;
    lastResultType = "number";
}

void LLVMCodeGen::visit(UnaryOpASTNode* node) {
    if (node->getOperand()) {
        node->getOperand()->accept(this);
    }
    std::string operandReg = lastResultReg;
    std::string operandType = lastResultType;
    std::string resultReg = newReg();

    if (node->getOp() == "!") {
        std::string condI1 = operandReg;
        if (operandType == "number") {
            condI1 = newReg();
            emitIndent();
            irStream << condI1 << " = fcmp one double " << operandReg << ", 0.000000e+00\n";
        }
        emitIndent();
        irStream << resultReg << " = xor i1 " << condI1 << ", true\n";
        lastResultReg = resultReg;
        lastResultType = "boolean";
    } else if (node->getOp() == "-") {
        emitIndent();
        irStream << resultReg << " = fneg double " << operandReg << "\n";
        lastResultReg = resultReg;
        lastResultType = "number";
    }
}

void LLVMCodeGen::visit(BinaryOpASTNode* node) {
    const std::string& op = node->getOp();

    if (op == "&&" || op == "||") {
        std::string rhsLabel = newLabel("log.rhs");
        std::string mergeLabel = newLabel("log.merge");

        node->getLeft()->accept(this);
        std::string lhsVal = lastResultReg;
        std::string lhsI1 = lhsVal;
        if (lastResultType == "number") {
            lhsI1 = newReg();
            emitIndent();
            irStream << lhsI1 << " = fcmp one double " << lhsVal << ", 0.000000e+00\n";
        }

        std::string lhsBlock = currentBlockLabel;
        std::string resReg = newReg();

        if (op == "&&") {
            emitIndent();
            irStream << "br i1 " << lhsI1 << ", label %" << rhsLabel << ", label %" << mergeLabel << "\n";
            irStream << rhsLabel << ":\n";
            currentBlockLabel = rhsLabel;

            node->getRight()->accept(this);
            std::string rhsVal = lastResultReg;
            std::string rhsI1 = rhsVal;
            if (lastResultType == "number") {
                rhsI1 = newReg();
                emitIndent();
                irStream << rhsI1 << " = fcmp one double " << rhsVal << ", 0.000000e+00\n";
            }
            std::string rhsBlock = currentBlockLabel;
            emitIndent();
            irStream << "br label %" << mergeLabel << "\n";

            irStream << mergeLabel << ":\n";
            currentBlockLabel = mergeLabel;
            emitIndent();
            irStream << resReg << " = phi i1 [ false, %" << lhsBlock << " ], [ " << rhsI1 << ", %" << rhsBlock << " ]\n";
        } else { // ||
            emitIndent();
            irStream << "br i1 " << lhsI1 << ", label %" << mergeLabel << ", label %" << rhsLabel << "\n";
            irStream << rhsLabel << ":\n";
            currentBlockLabel = rhsLabel;

            node->getRight()->accept(this);
            std::string rhsVal = lastResultReg;
            std::string rhsI1 = rhsVal;
            if (lastResultType == "number") {
                rhsI1 = newReg();
                emitIndent();
                irStream << rhsI1 << " = fcmp one double " << rhsVal << ", 0.000000e+00\n";
            }
            std::string rhsBlock = currentBlockLabel;
            emitIndent();
            irStream << "br label %" << mergeLabel << "\n";

            irStream << mergeLabel << ":\n";
            currentBlockLabel = mergeLabel;
            emitIndent();
            irStream << resReg << " = phi i1 [ true, %" << lhsBlock << " ], [ " << rhsI1 << ", %" << rhsBlock << " ]\n";
        }

        lastResultReg = resReg;
        lastResultType = "boolean";
        return;
    }

    node->getLeft()->accept(this);
    std::string lhs = lastResultReg;
    std::string lhsType = lastResultType;

    node->getRight()->accept(this);
    std::string rhs = lastResultReg;
    std::string rhsType = lastResultType;

    std::string resultReg = newReg();

    if (op == "+") {
        emitIndent();
        irStream << resultReg << " = fadd double " << lhs << ", " << rhs << "\n";
        lastResultType = "number";
    } else if (op == "-") {
        emitIndent();
        irStream << resultReg << " = fsub double " << lhs << ", " << rhs << "\n";
        lastResultType = "number";
    } else if (op == "*") {
        emitIndent();
        irStream << resultReg << " = fmul double " << lhs << ", " << rhs << "\n";
        lastResultType = "number";
    } else if (op == "/") {
        emitIndent();
        irStream << resultReg << " = fdiv double " << lhs << ", " << rhs << "\n";
        lastResultType = "number";
    } else if (op == ">" || op == "<" || op == "==" || op == "!=" || op == ">=" || op == "<=") {
        std::string condCode = "oeq";
        if (op == ">") condCode = "ogt";
        else if (op == "<") condCode = "olt";
        else if (op == "==") condCode = "oeq";
        else if (op == "!=") condCode = "one";
        else if (op == ">=") condCode = "oge";
        else if (op == "<=") condCode = "ole";

        emitIndent();
        irStream << resultReg << " = fcmp " << condCode << " double " << lhs << ", " << rhs << "\n";
        lastResultType = "boolean";
    }

    lastResultReg = resultReg;
}

void LLVMCodeGen::visit(IfASTNode* node) {
    node->getCondition()->accept(this);
    std::string condVal = lastResultReg;

    std::string condI1 = condVal;
    if (lastResultType == "number") {
        condI1 = newReg();
        emitIndent();
        irStream << condI1 << " = fcmp one double " << condVal << ", 0.000000e+00\n";
    }

    std::string thenLabel = newLabel("then");
    std::string elseLabel = newLabel("else");
    std::string mergeLabel = newLabel("merge");

    if (node->getElseBlock()) {
        emitIndent();
        irStream << "br i1 " << condI1 << ", label %" << thenLabel << ", label %" << elseLabel << "\n";

        irStream << thenLabel << ":\n";
        currentBlockLabel = thenLabel;
        node->getThenBlock()->accept(this);
        emitIndent();
        irStream << "br label %" << mergeLabel << "\n";

        irStream << elseLabel << ":\n";
        currentBlockLabel = elseLabel;
        node->getElseBlock()->accept(this);
        emitIndent();
        irStream << "br label %" << mergeLabel << "\n";
    } else {
        emitIndent();
        irStream << "br i1 " << condI1 << ", label %" << thenLabel << ", label %" << mergeLabel << "\n";

        irStream << thenLabel << ":\n";
        currentBlockLabel = thenLabel;
        node->getThenBlock()->accept(this);
        emitIndent();
        irStream << "br label %" << mergeLabel << "\n";
    }

    irStream << mergeLabel << ":\n";
    currentBlockLabel = mergeLabel;
}

void LLVMCodeGen::visit(WhileASTNode* node) {
    std::string condLabel = newLabel("while.cond");
    std::string bodyLabel = newLabel("while.body");
    std::string endLabel = newLabel("while.end");

    emitIndent();
    irStream << "br label %" << condLabel << "\n";

    irStream << condLabel << ":\n";
    currentBlockLabel = condLabel;
    node->getCondition()->accept(this);
    std::string condVal = lastResultReg;

    std::string condI1 = condVal;
    if (lastResultType == "number") {
        condI1 = newReg();
        emitIndent();
        irStream << condI1 << " = fcmp one double " << condVal << ", 0.000000e+00\n";
    }

    emitIndent();
    irStream << "br i1 " << condI1 << ", label %" << bodyLabel << ", label %" << endLabel << "\n";

    irStream << bodyLabel << ":\n";
    currentBlockLabel = bodyLabel;
    loopStack.push_back({endLabel, condLabel});
    if (node->getBody()) {
        node->getBody()->accept(this);
    }
    loopStack.pop_back();

    emitIndent();
    irStream << "br label %" << condLabel << "\n";

    irStream << endLabel << ":\n";
    currentBlockLabel = endLabel;
}

void LLVMCodeGen::visit(ForASTNode* node) {
    if (node->getInit()) {
        node->getInit()->accept(this);
    }

    std::string condLabel = newLabel("for.cond");
    std::string bodyLabel = newLabel("for.body");
    std::string stepLabel = newLabel("for.step");
    std::string endLabel = newLabel("for.end");

    emitIndent();
    irStream << "br label %" << condLabel << "\n";

    irStream << condLabel << ":\n";
    currentBlockLabel = condLabel;
    if (node->getCondition()) {
        node->getCondition()->accept(this);
        std::string condVal = lastResultReg;

        std::string condI1 = condVal;
        if (lastResultType == "number") {
            condI1 = newReg();
            emitIndent();
            irStream << condI1 << " = fcmp one double " << condVal << ", 0.000000e+00\n";
        }
        emitIndent();
        irStream << "br i1 " << condI1 << ", label %" << bodyLabel << ", label %" << endLabel << "\n";
    } else {
        emitIndent();
        irStream << "br label %" << bodyLabel << "\n";
    }

    irStream << bodyLabel << ":\n";
    currentBlockLabel = bodyLabel;
    loopStack.push_back({endLabel, stepLabel});
    if (node->getBody()) {
        node->getBody()->accept(this);
    }
    loopStack.pop_back();

    emitIndent();
    irStream << "br label %" << stepLabel << "\n";

    irStream << stepLabel << ":\n";
    currentBlockLabel = stepLabel;
    if (node->getUpdate()) {
        node->getUpdate()->accept(this);
    }
    emitIndent();
    irStream << "br label %" << condLabel << "\n";

    irStream << endLabel << ":\n";
    currentBlockLabel = endLabel;
}

void LLVMCodeGen::visit(BreakASTNode* node) {
    if (!loopStack.empty()) {
        emitIndent();
        irStream << "br label %" << loopStack.back().breakLabel << "\n";
    }
}

void LLVMCodeGen::visit(ContinueASTNode* node) {
    if (!loopStack.empty()) {
        emitIndent();
        irStream << "br label %" << loopStack.back().continueLabel << "\n";
    }
}

void LLVMCodeGen::visit(CallExprASTNode* node) {
    std::vector<std::string> argRegs;
    std::vector<std::string> argTypes;

    for (const auto& arg : node->getArgs()) {
        arg->accept(this);
        argRegs.push_back(lastResultReg);
        argTypes.push_back(lastResultType);
    }

    std::string retType = "number";
    auto it = functionReturnTypes.find(node->getCallee());
    if (it != functionReturnTypes.end()) {
        retType = it->second;
    }

    std::string llvmRetType = getLLVMType(retType);

    std::string callReg = "";
    emitIndent();
    if (llvmRetType != "void") {
        callReg = newReg();
        irStream << callReg << " = ";
    }
    irStream << "call " << llvmRetType << " @" << node->getCallee() << "(";
    for (size_t i = 0; i < argRegs.size(); ++i) {
        std::string pType = getLLVMType(argTypes[i]);
        irStream << pType << " " << argRegs[i];
        if (i + 1 < argRegs.size()) irStream << ", ";
    }
    irStream << ")\n";

    lastResultReg = callReg;
    lastResultType = retType;
}

void LLVMCodeGen::visit(PrintASTNode* node) {
    if (node->getExpression()) {
        node->getExpression()->accept(this);
        std::string valReg = lastResultReg;
        std::string valType = lastResultType;

        if (valType == "string") {
            std::string strPtr = newReg();
            emitIndent();
            irStream << strPtr << " = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0\n";
            std::string printCall = newReg();
            emitIndent();
            irStream << printCall << " = call i32 (i8*, ...) @printf(i8* " << strPtr << ", i8* " << valReg << ")\n";
        } else if (valType == "boolean") {
            std::string trueLabel = newLabel("print.true");
            std::string falseLabel = newLabel("print.false");
            std::string mergeLabel = newLabel("print.merge");

            emitIndent();
            irStream << "br i1 " << valReg << ", label %" << trueLabel << ", label %" << falseLabel << "\n";

            irStream << trueLabel << ":\n";
            currentBlockLabel = trueLabel;
            std::string ptrTrue = newReg();
            emitIndent();
            irStream << ptrTrue << " = getelementptr inbounds [6 x i8], [6 x i8]* @.fmt_bool_true, i64 0, i64 0\n";
            std::string printTrue = newReg();
            emitIndent();
            irStream << printTrue << " = call i32 (i8*, ...) @printf(i8* " << ptrTrue << ")\n";
            emitIndent();
            irStream << "br label %" << mergeLabel << "\n";

            irStream << falseLabel << ":\n";
            currentBlockLabel = falseLabel;
            std::string ptrFalse = newReg();
            emitIndent();
            irStream << ptrFalse << " = getelementptr inbounds [7 x i8], [7 x i8]* @.fmt_bool_false, i64 0, i64 0\n";
            std::string printFalse = newReg();
            emitIndent();
            irStream << printFalse << " = call i32 (i8*, ...) @printf(i8* " << ptrFalse << ")\n";
            emitIndent();
            irStream << "br label %" << mergeLabel << "\n";

            irStream << mergeLabel << ":\n";
            currentBlockLabel = mergeLabel;
        } else {
            // Default number
            std::string strPtr = newReg();
            emitIndent();
            irStream << strPtr << " = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_num, i64 0, i64 0\n";
            std::string printCall = newReg();
            emitIndent();
            irStream << printCall << " = call i32 (i8*, ...) @printf(i8* " << strPtr << ", double " << valReg << ")\n";
        }
    }
}

void LLVMCodeGen::visit(ReturnASTNode* node) {
    blockHasTerminator = true;
    if (node->getValue()) {
        node->getValue()->accept(this);
        std::string retVal = lastResultReg;
        std::string retType = lastResultType;

        std::string targetLLVMType = (currentFunctionReturnType == "boolean") ? "i1" :
                                     (currentFunctionReturnType == "string") ? "i8*" :
                                     (currentFunctionReturnType == "void") ? "void" : "double";

        if (targetLLVMType == "i1" && retType == "number") {
            std::string converted = newReg();
            emitIndent();
            irStream << converted << " = fcmp one double " << retVal << ", 0.000000e+00\n";
            retVal = converted;
        } else if (targetLLVMType == "double" && retType == "boolean") {
            std::string converted = newReg();
            emitIndent();
            irStream << converted << " = uitofp i1 " << retVal << " to double\n";
            retVal = converted;
        }

        emitIndent();
        irStream << "ret " << targetLLVMType << " " << retVal << "\n";
    } else {
        emitIndent();
        irStream << "ret void\n";
    }
}

} // namespace vit
