; ==========================================================
; ModuleID = 'vit_module'
; Generated by VIT Compiler (Phase 1 MVP)
; ==========================================================

source_filename = "vit_module.jslik"
target triple = "x86_64-pc-windows-msvc"

@.fmt_print = private unnamed_addr constant [4 x i8] c"%f\0A\00", align 1

declare i32 @printf(i8*, ...)

define double @add(double %a, double %b) {
entry:
  %a.addr = alloca double, align 8
  store double %a, double* %a.addr, align 8
  %b.addr = alloca double, align 8
  store double %b, double* %b.addr, align 8
  %t0 = load double, double* %a.addr, align 8
  %t1 = load double, double* %b.addr, align 8
  %t2 = fadd double %t0, %t1
  ret double %t2
}

define double @main() {
entry:
  %x.addr = alloca double, align 8
  store double 15.0, double* %x.addr, align 8
  %y.addr = alloca double, align 8
  store double 35.0, double* %y.addr, align 8
  %result.addr = alloca double, align 8
  %t0 = load double, double* %x.addr, align 8
  %t1 = load double, double* %y.addr, align 8
  %t2 = call double @add(double %t0, double %t1)
  store double %t2, double* %result.addr, align 8
  %t3 = load double, double* %result.addr, align 8
  %t5 = fcmp ogt double %t3, 30.0
  %t4 = uitofp i1 %t5 to double
  %t6 = fcmp one double %t4, 0.000000e+00
  br i1 %t6, label %then.0, label %else.1
then.0:
  %t7 = load double, double* %result.addr, align 8
  %t8 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_print, i64 0, i64 0
  %t9 = call i32 (i8*, ...) @printf(i8* %t8, double %t7)
  br label %merge.2
else.1:
  %t10 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_print, i64 0, i64 0
  %t11 = call i32 (i8*, ...) @printf(i8* %t10, double 0.0)
  br label %merge.2
merge.2:
  ret double 0.0
}

